import '../models/petpal_v12_models.dart';

class PetPalV12SeedRepository {
  const PetPalV12SeedRepository();

  List<RoomItemConfig> roomItems() => List.of(_roomItems);

  List<OfflineEventConfig> offlineEvents() => List.of(_offlineEvents);

  List<MomentConfig> moments() => List.of(_moments);

  MomentConfig? momentById(String id) {
    for (final moment in _moments) {
      if (moment.momentId == id) return moment;
    }
    return null;
  }
}

const _roomItems = [
  RoomItemConfig(
    itemId: 'food_bowl',
    itemName: 'Food Bowl',
    itemType: 'basic',
    petType: 'all',
    defaultRoomAssetUrl: 'assets/room_items/food_bowl.png',
    description: 'A little bowl that makes quiet snack checks more likely.',
    unlockAffinityLevel: 1,
    defaultUnlocked: true,
    displayOrder: 10,
    enabled: true,
    archived: false,
  ),
  RoomItemConfig(
    itemId: 'soft_blanket',
    itemName: 'Soft Blanket',
    itemType: 'comfort',
    petType: 'all',
    defaultRoomAssetUrl: 'assets/room_items/soft_blanket.png',
    description: 'A warm blanket for naps, dreams, and sleepy returns.',
    unlockAffinityLevel: 1,
    defaultUnlocked: true,
    displayOrder: 20,
    enabled: true,
    archived: false,
  ),
  RoomItemConfig(
    itemId: 'toy_ball',
    itemName: 'Toy Ball',
    itemType: 'toy',
    petType: 'all',
    defaultRoomAssetUrl: 'assets/room_items/toy_ball.png',
    description: 'A bouncy toy for tiny chases and room adventures.',
    unlockAffinityLevel: 1,
    defaultUnlocked: true,
    displayOrder: 30,
    enabled: true,
    archived: false,
  ),
  RoomItemConfig(
    itemId: 'cat_box',
    itemName: 'Cat Box',
    itemType: 'toy',
    petType: 'cat',
    defaultRoomAssetUrl: 'assets/room_items/cat_box.png',
    description: 'A perfect little hideout for curious cats.',
    unlockAffinityLevel: 3,
    defaultUnlocked: false,
    displayOrder: 40,
    enabled: true,
    archived: false,
  ),
  RoomItemConfig(
    itemId: 'window_cushion',
    itemName: 'Window Cushion',
    itemType: 'scene',
    petType: 'all',
    defaultRoomAssetUrl: 'assets/room_items/window_cushion.png',
    description: 'A sunny perch for window naps and quiet watching.',
    unlockAffinityLevel: 4,
    defaultUnlocked: false,
    displayOrder: 50,
    enabled: true,
    archived: false,
  ),
];

const _offlineEvents = [
  OfflineEventConfig(
    eventId: 'blanket_nap',
    eventName: 'Blanket Nap',
    eventType: 'sleep',
    petType: 'all',
    personalityTags: ['Lazy', 'Quiet', 'Sweet'],
    requiredItem: 'soft_blanket',
    relatedItems: ['soft_blanket'],
    itemWeightBonus: 16,
    timeWindow: ['all'],
    preferredTimeWindow: ['night', 'afternoon'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 60,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'blanket_nap',
    oncePerPet: false,
    titleTemplate: 'A Blanket Nap',
    bodyTemplate:
        '{pet_name} curled up on the soft blanket and saved the warmest corner for later.',
    imageKey: 'blanket_nap',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'window_nap',
    eventName: 'Window Nap',
    eventType: 'window',
    petType: 'all',
    personalityTags: ['Quiet', 'Gentle'],
    relatedItems: ['window_cushion'],
    itemWeightBonus: 18,
    timeWindow: ['afternoon', 'evening'],
    preferredTimeWindow: ['afternoon'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 44,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'window_nap',
    oncePerPet: false,
    titleTemplate: 'Window Nap',
    bodyTemplate:
        '{pet_name} watched the room get softer by the window, then dozed in the light.',
    imageKey: 'window_nap',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'door_waiting',
    eventName: 'Door Waiting',
    eventType: 'wait',
    petType: 'all',
    personalityTags: ['Affectionate', 'Shy'],
    relatedItems: [],
    itemWeightBonus: 0,
    timeWindow: ['all'],
    preferredTimeWindow: ['evening'],
    offlineMinMinutes: 240,
    affinityMinLevel: 1,
    baseWeight: 42,
    rewardMood: 2,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'door_waiting',
    oncePerPet: false,
    titleTemplate: 'By the Door',
    bodyTemplate:
        '{pet_name} spent a quiet minute near the door, then found something cozy to do.',
    imageKey: 'door_waiting',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'pillow_curl',
    eventName: 'Pillow Curl',
    eventType: 'sleep',
    petType: 'all',
    personalityTags: ['Lazy', 'Quiet'],
    relatedItems: ['soft_blanket'],
    itemWeightBonus: 14,
    timeWindow: ['night'],
    preferredTimeWindow: ['night'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 50,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: true,
    momentId: 'pillow_curl',
    oncePerPet: false,
    titleTemplate: 'A Sleepy Curl',
    bodyTemplate:
        'At night, {pet_name} tucked into a small circle and breathed in tiny sleepy beats.',
    imageKey: 'pillow_curl',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'tiny_dream',
    eventName: 'Tiny Dream',
    eventType: 'dream',
    petType: 'all',
    personalityTags: ['Sweet', 'Curious'],
    relatedItems: ['soft_blanket'],
    itemWeightBonus: 16,
    timeWindow: ['all'],
    preferredTimeWindow: ['night'],
    offlineMinMinutes: 180,
    moodMin: 70,
    affinityMinLevel: 1,
    baseWeight: 36,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'tiny_dream',
    oncePerPet: false,
    titleTemplate: 'Tiny Dream',
    bodyTemplate:
        '{pet_name} had a tiny dream and woke up looking like the room had told a secret.',
    imageKey: 'tiny_dream',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'food_bowl_watch',
    eventName: 'Bowl Watching',
    eventType: 'food',
    petType: 'all',
    personalityTags: ['Foodie'],
    relatedItems: ['food_bowl'],
    itemWeightBonus: 18,
    timeWindow: ['all'],
    preferredTimeWindow: ['morning', 'evening'],
    offlineMinMinutes: 120,
    hungerMax: 49,
    affinityMinLevel: 1,
    baseWeight: 56,
    rewardMood: 1,
    rewardHunger: 2,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'Bowl Check',
    bodyTemplate:
        '{pet_name} checked the food bowl, then waited patiently for the next meal.',
    imageKey: 'food_bowl_watch',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'after_meal_nap',
    eventName: 'After Meal Nap',
    eventType: 'sleep',
    petType: 'all',
    personalityTags: ['Foodie', 'Lazy'],
    relatedItems: ['food_bowl', 'soft_blanket'],
    itemWeightBonus: 10,
    timeWindow: ['all'],
    preferredTimeWindow: ['afternoon'],
    offlineMinMinutes: 120,
    hungerMin: 80,
    affinityMinLevel: 1,
    baseWeight: 38,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'After-Meal Nap',
    bodyTemplate:
        'With a full little belly, {pet_name} took a peaceful nap nearby.',
    imageKey: 'after_meal_nap',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'quiet_corner',
    eventName: 'Quiet Corner',
    eventType: 'mood',
    petType: 'all',
    personalityTags: ['Quiet', 'Shy'],
    relatedItems: [],
    itemWeightBonus: 0,
    timeWindow: ['all'],
    preferredTimeWindow: ['evening', 'night'],
    offlineMinMinutes: 180,
    moodMax: 59,
    affinityMinLevel: 1,
    baseWeight: 48,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'Quiet Corner',
    bodyTemplate:
        '{pet_name} picked a quiet corner and settled there until the room felt calmer.',
    imageKey: 'quiet_corner',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'happy_roll',
    eventName: 'Happy Roll',
    eventType: 'mood',
    petType: 'dog',
    personalityTags: ['Playful', 'Affectionate'],
    relatedItems: ['toy_ball'],
    itemWeightBonus: 12,
    timeWindow: ['all'],
    preferredTimeWindow: ['morning', 'afternoon'],
    offlineMinMinutes: 120,
    moodMin: 80,
    affinityMinLevel: 1,
    baseWeight: 44,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'happy_roll',
    oncePerPet: false,
    titleTemplate: 'Happy Roll',
    bodyTemplate:
        '{pet_name} rolled across the rug in a very serious display of joy.',
    imageKey: 'happy_roll',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'toy_chase',
    eventName: 'Toy Chase',
    eventType: 'play',
    petType: 'dog',
    personalityTags: ['Playful'],
    requiredItem: 'toy_ball',
    relatedItems: ['toy_ball'],
    itemWeightBonus: 22,
    timeWindow: ['all'],
    preferredTimeWindow: ['morning', 'afternoon'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 54,
    rewardMood: 5,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'toy_chase',
    oncePerPet: false,
    titleTemplate: 'Toy Chase',
    bodyTemplate:
        '{pet_name} chased the toy ball in three proud circles, then guarded it like treasure.',
    imageKey: 'toy_chase',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'ball_under_bed',
    eventName: 'Ball Under Bed',
    eventType: 'object',
    petType: 'dog',
    personalityTags: ['Playful', 'Curious'],
    requiredItem: 'toy_ball',
    relatedItems: ['toy_ball'],
    itemWeightBonus: 18,
    timeWindow: ['all'],
    preferredTimeWindow: ['afternoon'],
    offlineMinMinutes: 180,
    affinityMinLevel: 1,
    baseWeight: 38,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'Under the Bed',
    bodyTemplate:
        '{pet_name} nudged the toy ball under the bed and looked very pleased with the puzzle.',
    imageKey: 'ball_under_bed',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'welcome_wiggle',
    eventName: 'Welcome Wiggle',
    eventType: 'mood',
    petType: 'dog',
    personalityTags: ['Affectionate', 'Playful'],
    relatedItems: [],
    itemWeightBonus: 0,
    timeWindow: ['all'],
    preferredTimeWindow: ['evening'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 46,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'Welcome Wiggle',
    bodyTemplate:
        '{pet_name} did a little welcome wiggle before remembering to act composed.',
    imageKey: 'welcome_wiggle',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'box_hideout',
    eventName: 'Box Hideout',
    eventType: 'object',
    petType: 'cat',
    personalityTags: ['Curious', 'Shy', 'Sassy'],
    requiredItem: 'cat_box',
    relatedItems: ['cat_box'],
    itemWeightBonus: 24,
    timeWindow: ['all'],
    preferredTimeWindow: ['afternoon', 'evening'],
    offlineMinMinutes: 120,
    affinityMinLevel: 3,
    baseWeight: 52,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'box_hideout',
    oncePerPet: false,
    titleTemplate: 'Box Hideout',
    bodyTemplate:
        '{pet_name} discovered the box and became almost entirely invisible, except for two bright eyes.',
    imageKey: 'box_hideout',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'tail_peek',
    eventName: 'Tail Peek',
    eventType: 'object',
    petType: 'cat',
    personalityTags: ['Sassy', 'Shy'],
    requiredItem: 'cat_box',
    relatedItems: ['cat_box'],
    itemWeightBonus: 20,
    timeWindow: ['all'],
    preferredTimeWindow: ['evening'],
    offlineMinMinutes: 180,
    affinityMinLevel: 3,
    baseWeight: 42,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'tail_peek',
    oncePerPet: false,
    titleTemplate: 'Tail Peek',
    bodyTemplate:
        'Only {pet_name}\'s tail peeked out for a while. The rest was classified box business.',
    imageKey: 'tail_peek',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'sunbeam_stretch',
    eventName: 'Sunbeam Stretch',
    eventType: 'window',
    petType: 'cat',
    personalityTags: ['Lazy', 'Gentle'],
    relatedItems: ['window_cushion'],
    itemWeightBonus: 20,
    timeWindow: ['morning', 'afternoon'],
    preferredTimeWindow: ['morning'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 50,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'sunbeam_stretch',
    oncePerPet: false,
    titleTemplate: 'Sunbeam Stretch',
    bodyTemplate:
        '{pet_name} found a sunbeam and stretched until the whole room looked warmer.',
    imageKey: 'sunbeam_stretch',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'goodnight_purr',
    eventName: 'Goodnight Purr',
    eventType: 'sleep',
    petType: 'cat',
    personalityTags: ['Affectionate', 'Quiet'],
    relatedItems: ['soft_blanket'],
    itemWeightBonus: 10,
    timeWindow: ['night'],
    preferredTimeWindow: ['night'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 46,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'Goodnight Purr',
    bodyTemplate:
        '{pet_name} spent the quiet night purring softly and keeping the room company.',
    imageKey: 'goodnight_purr',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'curtain_watch',
    eventName: 'Curtain Watch',
    eventType: 'window',
    petType: 'cat',
    personalityTags: ['Curious', 'Cool'],
    relatedItems: ['window_cushion'],
    itemWeightBonus: 18,
    timeWindow: ['all'],
    preferredTimeWindow: ['morning', 'evening'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 42,
    rewardMood: 3,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'curtain_watch',
    oncePerPet: false,
    titleTemplate: 'Curtain Watch',
    bodyTemplate:
        '{pet_name} sat by the curtain and observed important room mysteries.',
    imageKey: 'curtain_watch',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'tiny_troublemaker',
    eventName: 'Tiny Troublemaker',
    eventType: 'play',
    petType: 'all',
    personalityTags: ['Playful', 'Curious'],
    relatedItems: ['toy_ball'],
    itemWeightBonus: 18,
    timeWindow: ['all'],
    preferredTimeWindow: ['afternoon'],
    offlineMinMinutes: 180,
    affinityMinLevel: 1,
    baseWeight: 38,
    rewardMood: 4,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'tiny_troublemaker',
    oncePerPet: false,
    titleTemplate: 'Tiny Troublemaker',
    bodyTemplate:
        '{pet_name} rearranged one tiny thing and looked extremely innocent afterward.',
    imageKey: 'tiny_troublemaker',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'missed_you',
    eventName: 'Missed You',
    eventType: 'wait',
    petType: 'all',
    personalityTags: ['Affectionate', 'Sweet'],
    relatedItems: [],
    itemWeightBonus: 0,
    timeWindow: ['all'],
    preferredTimeWindow: ['evening', 'night'],
    offlineMinMinutes: 360,
    affinityMinLevel: 1,
    baseWeight: 42,
    rewardMood: 2,
    rewardHunger: 0,
    rewardAffinity: 0,
    canUnlockMoment: false,
    oncePerPet: false,
    titleTemplate: 'A Quiet Wait',
    bodyTemplate:
        '{pet_name} kept the room company and perked up when home felt close again.',
    imageKey: 'missed_you',
    enabled: true,
    archived: false,
  ),
  OfflineEventConfig(
    eventId: 'first_little_memory',
    eventName: 'First Little Memory',
    eventType: 'special',
    petType: 'all',
    personalityTags: [],
    relatedItems: [],
    itemWeightBonus: 0,
    timeWindow: ['all'],
    preferredTimeWindow: ['all'],
    offlineMinMinutes: 120,
    affinityMinLevel: 1,
    baseWeight: 26,
    rewardMood: 2,
    rewardHunger: 0,
    rewardAffinity: 1,
    canUnlockMoment: true,
    momentId: 'first_little_memory',
    oncePerPet: true,
    titleTemplate: 'First Little Memory',
    bodyTemplate:
        'A small quiet moment with {pet_name} turned into something worth keeping.',
    imageKey: 'first_little_memory',
    enabled: true,
    archived: false,
  ),
];

const _moments = [
  MomentConfig(
    momentId: 'blanket_nap',
    title: 'Blanket Nap',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} chose the soft blanket today. It looked like a tiny promise to rest well.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 10,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'window_nap',
    title: 'Window Nap',
    momentType: 'home',
    diaryTemplate:
        'The window light found {pet_name}, and {pet_name} let the afternoon become a nap.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 20,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'door_waiting',
    title: 'By the Door',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} waited by the door for a moment, then carried on with a brave little day.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 30,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'pillow_curl',
    title: 'Sleepy Curl',
    momentType: 'home',
    diaryTemplate:
        'Tonight, {pet_name} curled up so neatly that the room seemed to whisper goodnight.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 40,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'tiny_dream',
    title: 'Tiny Dream',
    momentType: 'dream',
    diaryTemplate:
        '{pet_name} woke from a tiny dream with a look that said the dream was kind.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 50,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'happy_roll',
    title: 'Happy Roll',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} rolled around with such delight that the floor briefly became a playground.',
    petType: 'dog',
    sourceType: 'offline_event',
    displayOrder: 60,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'toy_chase',
    title: 'Toy Chase',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} chased the toy ball, won a private race, and looked very proud.',
    petType: 'dog',
    sourceType: 'offline_event',
    displayOrder: 70,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'box_hideout',
    title: 'Box Hideout',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} found the cat box and became a small expert in hiding beautifully.',
    petType: 'cat',
    sourceType: 'offline_event',
    displayOrder: 80,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'tail_peek',
    title: 'Tail Peek',
    momentType: 'home',
    diaryTemplate:
        'For a while, only {pet_name}\'s tail was visible. It was enough to make the room smile.',
    petType: 'cat',
    sourceType: 'offline_event',
    displayOrder: 90,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'sunbeam_stretch',
    title: 'Sunbeam Stretch',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} stretched in the sunbeam and made the whole room feel slower.',
    petType: 'cat',
    sourceType: 'offline_event',
    displayOrder: 100,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'curtain_watch',
    title: 'Curtain Watch',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} watched the curtain as if it might reveal a secret at any second.',
    petType: 'cat',
    sourceType: 'offline_event',
    displayOrder: 110,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'tiny_troublemaker',
    title: 'Tiny Troublemaker',
    momentType: 'home',
    diaryTemplate:
        '{pet_name} caused one harmless little mystery and looked impossible to accuse.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 120,
    enabled: true,
    archived: false,
  ),
  MomentConfig(
    momentId: 'first_little_memory',
    title: 'First Little Memory',
    momentType: 'special',
    diaryTemplate:
        'This was the first small memory {pet_name} made at home. Small, warm, and worth keeping.',
    petType: 'all',
    sourceType: 'offline_event',
    displayOrder: 130,
    enabled: true,
    archived: false,
  ),
];
